spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: test-group-id
    properties:
      specific:
        avro:
          reader: true
      schema:
        registry:
          url: "http://localhost:8081"

mskafkatest:
  kafka:
    topic:
      name: topic_order
    avro:
      topic:
        name: avro_topic_name
